services:
  - type: web
    name: temi-clips-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NODE_ENV
        value: production